import Head from 'next/head'
import NavBar from '../components/NavBar'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Tekkadan | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
    </div>
  )
}

export default Home
